# Generated by Django 3.2 on 2021-05-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=128)),
                ('cost', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('hourly_pay', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
                ('application_link', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], max_length=10)),
                ('major', models.CharField(max_length=64)),
                ('uni_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('gpa', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
