# Generated by Django 3.2 on 2021-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
