# Generated by Django 3.2 on 2021-05-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_housing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('Housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
            ],
        ),
    ]
