# Generated by Django 3.2 on 2021-05-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210515_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Housing',
            new_name='housing',
        ),
    ]
