# Generated by Django 3.2 on 2021-05-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210515_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='description',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
