# Generated by Django 3.2 on 2021-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_housing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.CharField(default='null', max_length=2000),
        ),
    ]
